# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
             
    - run: |
         
          
          sudo apt-get update
          ls && pwd
          cp dist/postfolio/* .
   #       rm -rf node_modules  sudo npm install -g @angular/cli
    #      rm -rf dist
     #     npm install
      #    ng build
          
      #    ls -al
#     - name: Copy Directory
#   # You may pin to the exact commit or the version.
#   # uses: MadaraUchiha/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
#       uses: MadaraUchiha/copy-action@0.0.1
#       with:
#     # Source file
#         source: ./dist/portfolio/*
         
#     # Target file
#         target: .
#     - name: Copy folder content recursively to remote
#       uses: garygrossgarten/github-action-scp@release
#       with:
#           local: dist/portfolio
#           remote: portfolio
#           host: 20.124.8.234
#           username: ${{ secrets.vmusername }}
#           password: ${{ secrets.vmpassword }}



# cp dist/* /home/azuretest/portfolio/dist/

 #apt-get -qq install zip curl
#  npm cache clean --force
#     - name: 📂 Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.2.0
#       with:
#         server: 20.124.8.234
#         username: ${{ secrets.vmusername }}
#         password: ${{ secrets.vmpassword }}
#         local-dir: dist/
#         server-dir: /home/azuretest/portfolio/
    - name: test
      run: ls
     
